name: Terraform CI/CD

on:
  push:
    branches:
      - feature/*

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Format
        run: terraform fmt -check -recursive

      - name: Terraform Plan
        run: terraform plan

      - name: Terraform Scan
        run: |
          # Add commands to perform security scans or other checks on your Terraform code
          # For example, you can use tfsec or Checkov
          # Replace the command with the appropriate scanning tool you want to use
          tfsec .
          # checkov .

      # - name: Terraform Apply
      #   run: terraform apply --auto-approve

      - name: Commit Workflow
        run: |
          git config user.name "GitHub Actions"
          git config user.email "jitesh.awsfree2@gmail.com"
          git add -A
          git commit -m "Add GitHub Actions workflow" --allow-empty
          git push
